version: '3.7'
services:
  hidden-marketplace:
    image: nginx
    container_name: "hidden-marketplace"
    volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf
      - ./code:/usr/share/nginx/html
    ports:
      - 12700:80
    networks:
      - marketplace-net
    restart: always  

networks:
  marketplace-net: {}
